<?php
// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile


use \Codeception\Maybe;
use Codeception\Module\PhpBrowser;
use Codeception\Module\Filesystem;
use Codeception\Module\OtherHelper;

/**
 * Inherited methods
 * @method void execute($callable)
 * @method void wantToTest($text)
 * @method void wantTo($text)
 * @method void expectTo($prediction)
 * @method void expect($prediction)
 * @method void amGoingTo($argumentation)
 * @method void am($role)
 * @method void lookForwardTo($achieveValue)
*/

class AbsolutelyOtherGuy extends \Codeception\AbstractGuy
{
    
    /**
     * -> This method is proxified to corresponding module.
     *
     * Submits a form located on page.
     * Specify the form by it's css or xpath selector.
     * Fill the form fields values as array.
     *
     * Skipped fields will be filled by their values from page.
     * You don't need to click the 'Submit' button afterwards.
     * This command itself triggers the request to form's action.
     *
     * Examples:
     *
     * ``` php
     * <?php
     * $I->submitForm('#login', array('login' => 'davert', 'password' => '123456'));
     *
     * ```
     *
     * For sample Sign Up form:
     *
     * ``` html
     * <form action="/sign_up">
     *     Login: <input type="text" name="user[login]" /><br/>
     *     Password: <input type="password" name="user[password]" /><br/>
     *     Do you agree to out terms? <input type="checkbox" name="user[agree]" /><br/>
     *     Select pricing plan <select name="plan"><option value="1">Free</option><option value="2" selected="selected">Paid</option></select>
     *     <input type="submit" value="Submit" />
     * </form>
     * ```
     * I can write this:
     *
     * ``` php
     * <?php
     * $I->submitForm('#userForm', array('user' => array('login' => 'Davert', 'password' => '123456', 'agree' => true)));
     *
     * ```
     * Note, that pricing plan will be set to Paid, as it's selected on page.
     *
     * @param $selector
     * @param $params
     * @see Codeception\Module\PhpBrowser::submitForm()
     */
    public function submitForm($selector, $params) {
        $step = new \Codeception\Step\Action('submitForm', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * If your page triggers an ajax request, you can perform it manually.
     * This action sends a POST ajax request with specified params.
     * Additional params can be passed as array.
     *
     * Example:
     *
     * Imagine that by clicking checkbox you trigger ajax request which updates user settings.
     * We emulate that click by running this ajax request manually.
     *
     * ``` php
     * <?php
     * $I->sendAjaxPostRequest('/updateSettings', array('notifications' => true)); // POST
     * $I->sendAjaxGetRequest('/updateSettings', array('notifications' => true)); // GET
     *
     * ```
     *
     * @param $uri
     * @param $params
     * @see Codeception\Module\PhpBrowser::sendAjaxPostRequest()
     */
    public function sendAjaxPostRequest($uri, $params = null) {
        $step = new \Codeception\Step\Action('sendAjaxPostRequest', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * If your page triggers an ajax request, you can perform it manually.
     * This action sends a GET ajax request with specified params.
     *
     * See ->sendAjaxPostRequest for examples.
     *
     * @param $uri
     * @param $params
     * @see Codeception\Module\PhpBrowser::sendAjaxGetRequest()
     */
    public function sendAjaxGetRequest($uri, $params = null) {
        $step = new \Codeception\Step\Action('sendAjaxGetRequest', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * If your page triggers an ajax request, you can perform it manually.
     * This action sends an ajax request with specified method and params.
     *
     * Example:
     *
     * You need to perform an ajax request specifying the HTTP method.
     *
     * ``` php
     * <?php
     * $I->sendAjaxRequest('PUT', /posts/7', array('title' => 'new title');
     *
     * ```
     *
     * @param $method
     * @param $uri
     * @param $params
     * @see Codeception\Module\PhpBrowser::sendAjaxRequest()
     */
    public function sendAjaxRequest($method, $uri, $params = null) {
        $step = new \Codeception\Step\Action('sendAjaxRequest', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Asserts that current page has 404 response status code.
    * Conditional Assertion: Test won't be stopped on fail
     * @see Codeception\Module\PhpBrowser::seePageNotFound()
     */
    public function canSeePageNotFound() {
        $step = new \Codeception\Step\ConditionalAssertion('seePageNotFound', func_get_args());
        return $this->scenario->runStep($step);
    }
    /**
     * -> This method is proxified to corresponding module.
     *
     * Asserts that current page has 404 response status code.
     * @see Codeception\Module\PhpBrowser::seePageNotFound()
     */
    public function seePageNotFound() {
        $step = new \Codeception\Step\Assertion('seePageNotFound', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks that response code is equal to value provided.
     *
     * @param $code
     * @return mixed
    * Conditional Assertion: Test won't be stopped on fail
     * @see Codeception\Module\PhpBrowser::seeResponseCodeIs()
     */
    public function canSeeResponseCodeIs($code) {
        $step = new \Codeception\Step\ConditionalAssertion('seeResponseCodeIs', func_get_args());
        return $this->scenario->runStep($step);
    }
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks that response code is equal to value provided.
     *
     * @param $code
     * @return mixed
     * @see Codeception\Module\PhpBrowser::seeResponseCodeIs()
     */
    public function seeResponseCodeIs($code) {
        $step = new \Codeception\Step\Assertion('seeResponseCodeIs', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Adds HTTP authentication via username/password.
     *
     * @param $username
     * @param $password
     * @see Codeception\Module\PhpBrowser::amHttpAuthenticated()
     */
    public function amHttpAuthenticated($username, $password) {
        $step = new \Codeception\Step\Condition('amHttpAuthenticated', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Low-level API method.
     * If Codeception commands are not enough, use [Guzzle HTTP Client](http://guzzlephp.org/) methods directly
     *
     * Example:
     *
     * ``` php
     * <?php
     * // from the official Guzzle manual
     * $I->amGoingTo('Sign all requests with OAuth');
     * $I->executeInGuzzle(function (\Guzzle\Http\Client $client) {
     *      $client->addSubscriber(new Guzzle\Plugin\Oauth\OauthPlugin(array(
     *                  'consumer_key'    => '***',
     *                  'consumer_secret' => '***',
     *                  'token'           => '***',
     *                  'token_secret'    => '***'
     *      )));
     * });
     * ?>
     * ```
     *
     * It is not recommended to use this command on a regular basis.
     * If Codeception lacks important Guzzle Client methods, implement them and submit patches.
     *
     * @param callable $function
     * @see Codeception\Module\PhpBrowser::executeInGuzzle()
     */
    public function executeInGuzzle($function) {
        $step = new \Codeception\Step\Action('executeInGuzzle', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Assert if the specified checkbox is checked.
     * Use css selector or xpath to match.
     *
     * Example:
     *
     * ``` php
     * <?php
     * $I->seeCheckboxIsChecked('#agree'); // I suppose user agreed to terms
     * $I->seeCheckboxIsChecked('#signup_form input[type=checkbox]'); // I suppose user agreed to terms, If there is only one checkbox in form.
     * $I->seeCheckboxIsChecked('//form/input[@type=checkbox and @name=agree]');
     * ?>
     * ```
     *
     * @param $checkbox
    * Conditional Assertion: Test won't be stopped on fail
     * @see Codeception\Module\PhpBrowser::seeCheckboxIsChecked()
     */
    public function canSeeCheckboxIsChecked($checkbox) {
        $step = new \Codeception\Step\ConditionalAssertion('seeCheckboxIsChecked', func_get_args());
        return $this->scenario->runStep($step);
    }
    /**
     * -> This method is proxified to corresponding module.
     *
     * Assert if the specified checkbox is checked.
     * Use css selector or xpath to match.
     *
     * Example:
     *
     * ``` php
     * <?php
     * $I->seeCheckboxIsChecked('#agree'); // I suppose user agreed to terms
     * $I->seeCheckboxIsChecked('#signup_form input[type=checkbox]'); // I suppose user agreed to terms, If there is only one checkbox in form.
     * $I->seeCheckboxIsChecked('//form/input[@type=checkbox and @name=agree]');
     * ?>
     * ```
     *
     * @param $checkbox
     * @see Codeception\Module\PhpBrowser::seeCheckboxIsChecked()
     */
    public function seeCheckboxIsChecked($checkbox) {
        $step = new \Codeception\Step\Assertion('seeCheckboxIsChecked', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Assert if the specified checkbox is unchecked.
     * Use css selector or xpath to match.
     *
     * Example:
     *
     * ``` php
     * <?php
     * $I->dontSeeCheckboxIsChecked('#agree'); // I suppose user didn't agree to terms
     * $I->seeCheckboxIsChecked('#signup_form input[type=checkbox]'); // I suppose user didn't check the first checkbox in form.
     * ?>
     * ```
     *
     * @param $checkbox
    * Conditional Assertion: Test won't be stopped on fail
     * @see Codeception\Module\PhpBrowser::dontSeeCheckboxIsChecked()
     */
    public function cantSeeCheckboxIsChecked($checkbox) {
        $step = new \Codeception\Step\ConditionalAssertion('dontSeeCheckboxIsChecked', func_get_args());
        return $this->scenario->runStep($step);
    }
    /**
     * -> This method is proxified to corresponding module.
     *
     * Assert if the specified checkbox is unchecked.
     * Use css selector or xpath to match.
     *
     * Example:
     *
     * ``` php
     * <?php
     * $I->dontSeeCheckboxIsChecked('#agree'); // I suppose user didn't agree to terms
     * $I->seeCheckboxIsChecked('#signup_form input[type=checkbox]'); // I suppose user didn't check the first checkbox in form.
     * ?>
     * ```
     *
     * @param $checkbox
     * @see Codeception\Module\PhpBrowser::dontSeeCheckboxIsChecked()
     */
    public function dontSeeCheckboxIsChecked($checkbox) {
        $step = new \Codeception\Step\Assertion('dontSeeCheckboxIsChecked', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Opens the page.
     *
     * @param $page
     * @see Codeception\Util\Mink::amOnPage()
     */
    public function amOnPage($page) {
        $step = new \Codeception\Step\Condition('amOnPage', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Sets 'url' configuration parameter to hosts subdomain.
     * It does not open a page on subdomain. Use `amOnPage` for that
     *
     * ``` php
     * <?php
     * // If config is: 'http://mysite.com'
     * // or config is: 'http://www.mysite.com'
     * // or config is: 'http://company.mysite.com'
     *
     * $I->amOnSubdomain('user');
     * $I->amOnPage('/');
     * // moves to http://user.mysite.com/
     * ?>
     * ```
     * @param $subdomain
     * @return mixed
     * @see Codeception\Util\Mink::amOnSubdomain()
     */
    public function amOnSubdomain($subdomain) {
        $step = new \Codeception\Step\Condition('amOnSubdomain', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * @param string $text
     * @param string $selector
     *
     * @return void
    * Conditional Assertion: Test won't be stopped on fail
     * @see Codeception\Util\Mink::dontSee()
     */
    public function cantSee($text, $selector = null) {
        $step = new \Codeception\Step\ConditionalAssertion('dontSee', func_get_args());
        return $this->scenario->runStep($step);
    }
    /**
     * -> This method is proxified to corresponding module.
     *
     * @param string $text
     * @param string $selector
     *
     * @return void
     * @see Codeception\Util\Mink::dontSee()
     */
    public function dontSee($text, $selector = null) {
        $step = new \Codeception\Step\Assertion('dontSee', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Check if current page contains the text specified.
     * Specify the css selector to match only specific region.
     *
     * Examples:
     *
     * ``` php
     * <?php
     * $I->see('Logout'); // I can suppose user is logged in
     * $I->see('Sign Up','h1'); // I can suppose it's a signup page
     * $I->see('Sign Up','//body/h1'); // with XPath
     * ?>
     * ```
     *
     * @param $text
     * @param null $selector
    * Conditional Assertion: Test won't be stopped on fail
     * @see Codeception\Util\Mink::see()
     */
    public function canSee($text, $selector = null) {
        $step = new \Codeception\Step\ConditionalAssertion('see', func_get_args());
        return $this->scenario->runStep($step);
    }
    /**
     * -> This method is proxified to corresponding module.
     *
     * Check if current page contains the text specified.
     * Specify the css selector to match only specific region.
     *
     * Examples:
     *
     * ``` php
     * <?php
     * $I->see('Logout'); // I can suppose user is logged in
     * $I->see('Sign Up','h1'); // I can suppose it's a signup page
     * $I->see('Sign Up','//body/h1'); // with XPath
     * ?>
     * ```
     *
     * @param $text
     * @param null $selector
     * @see Codeception\Util\Mink::see()
     */
    public function see($text, $selector = null) {
        $step = new \Codeception\Step\Assertion('see', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks if there is a link with text specified.
     * Specify url to match link with exact this url.
     *
     * Examples:
     *
     * ``` php
     * <?php
     * $I->seeLink('Logout'); // matches <a href="#">Logout</a>
     * $I->seeLink('Logout','/logout'); // matches <a href="/logout">Logout</a>
     * ?>
     * ```
     *
     * @param $text
     * @param null $url
    * Conditional Assertion: Test won't be stopped on fail
     * @see Codeception\Util\Mink::seeLink()
     */
    public function canSeeLink($text, $url = null) {
        $step = new \Codeception\Step\ConditionalAssertion('seeLink', func_get_args());
        return $this->scenario->runStep($step);
    }
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks if there is a link with text specified.
     * Specify url to match link with exact this url.
     *
     * Examples:
     *
     * ``` php
     * <?php
     * $I->seeLink('Logout'); // matches <a href="#">Logout</a>
     * $I->seeLink('Logout','/logout'); // matches <a href="/logout">Logout</a>
     * ?>
     * ```
     *
     * @param $text
     * @param null $url
     * @see Codeception\Util\Mink::seeLink()
     */
    public function seeLink($text, $url = null) {
        $step = new \Codeception\Step\Assertion('seeLink', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks if page doesn't contain the link with text specified.
     * Specify url to narrow the results.
     *
     * Examples:
     *
     * ``` php
     * <?php
     * $I->dontSeeLink('Logout'); // I suppose user is not logged in
     * ?>
     * ```
     *
     * @param $text
     * @param null $url
    * Conditional Assertion: Test won't be stopped on fail
     * @see Codeception\Util\Mink::dontSeeLink()
     */
    public function cantSeeLink($text, $url = null) {
        $step = new \Codeception\Step\ConditionalAssertion('dontSeeLink', func_get_args());
        return $this->scenario->runStep($step);
    }
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks if page doesn't contain the link with text specified.
     * Specify url to narrow the results.
     *
     * Examples:
     *
     * ``` php
     * <?php
     * $I->dontSeeLink('Logout'); // I suppose user is not logged in
     * ?>
     * ```
     *
     * @param $text
     * @param null $url
     * @see Codeception\Util\Mink::dontSeeLink()
     */
    public function dontSeeLink($text, $url = null) {
        $step = new \Codeception\Step\Assertion('dontSeeLink', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Perform a click on link or button.
     * Link or button are found by their names or CSS selector.
     * Submits a form if button is a submit type.
     *
     * If link is an image it's found by alt attribute value of image.
     * If button is image button is found by it's value
     * If link or button can't be found by name they are searched by CSS selector.
     *
     * The second parameter is a context: CSS or XPath locator to narrow the search.
     *
     * Examples:
     *
     * ``` php
     * <?php
     * // simple link
     * $I->click('Logout');
     * // button of form
     * $I->click('Submit');
     * // CSS button
     * $I->click('#form input[type=submit]');
     * // XPath
     * $I->click('//form/*[@type=submit]')
     * // link in context
     * $I->click('Logout', '#nav');
     * ?>
     * ```
     * @param $link
     * @param $context
     * @see Codeception\Util\Mink::click()
     */
    public function click($link, $context = null) {
        $step = new \Codeception\Step\Action('click', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks if element exists on a page, matching it by CSS or XPath
     *
     * ``` php
     * <?php
     * $I->seeElement('.error');
     * $I->seeElement('//form/input[1]');
     * ?>
     * ```
     * @param $selector
    * Conditional Assertion: Test won't be stopped on fail
     * @see Codeception\Util\Mink::seeElement()
     */
    public function canSeeElement($selector) {
        $step = new \Codeception\Step\ConditionalAssertion('seeElement', func_get_args());
        return $this->scenario->runStep($step);
    }
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks if element exists on a page, matching it by CSS or XPath
     *
     * ``` php
     * <?php
     * $I->seeElement('.error');
     * $I->seeElement('//form/input[1]');
     * ?>
     * ```
     * @param $selector
     * @see Codeception\Util\Mink::seeElement()
     */
    public function seeElement($selector) {
        $step = new \Codeception\Step\Assertion('seeElement', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks if element does not exist (or is visible) on a page, matching it by CSS or XPath
     *
     * Example:
     * 
     * ``` php
     * <?php
     * $I->dontSeeElement('.error');
     * $I->dontSeeElement('//form/input[1]');
     * ?>
     * ```
     * @param $selector
    * Conditional Assertion: Test won't be stopped on fail
     * @see Codeception\Util\Mink::dontSeeElement()
     */
    public function cantSeeElement($selector) {
        $step = new \Codeception\Step\ConditionalAssertion('dontSeeElement', func_get_args());
        return $this->scenario->runStep($step);
    }
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks if element does not exist (or is visible) on a page, matching it by CSS or XPath
     *
     * Example:
     * 
     * ``` php
     * <?php
     * $I->dontSeeElement('.error');
     * $I->dontSeeElement('//form/input[1]');
     * ?>
     * ```
     * @param $selector
     * @see Codeception\Util\Mink::dontSeeElement()
     */
    public function dontSeeElement($selector) {
        $step = new \Codeception\Step\Assertion('dontSeeElement', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Reloads current page
     * @see Codeception\Util\Mink::reloadPage()
     */
    public function reloadPage() {
        $step = new \Codeception\Step\Action('reloadPage', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Moves back in history
     * @see Codeception\Util\Mink::moveBack()
     */
    public function moveBack() {
        $step = new \Codeception\Step\Action('moveBack', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Moves forward in history
     * @see Codeception\Util\Mink::moveForward()
     */
    public function moveForward() {
        $step = new \Codeception\Step\Action('moveForward', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Fills a text field or textarea with value.
     * 
     * Example:
     * 
     * ``` php
     * <?php
     * $I->fillField("//input[@type='text']", "Hello World!");
     * ?>
     * ```
     *
     * @param $field
     * @param $value
     * @see Codeception\Util\Mink::fillField()
     */
    public function fillField($field, $value) {
        $step = new \Codeception\Step\Action('fillField', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Selects an option in select tag or in radio button group.
     *
     * Example:
     *
     * ``` php
     * <?php
     * $I->selectOption('form select[name=account]', 'Premium');
     * $I->selectOption('form input[name=payment]', 'Monthly');
     * $I->selectOption('//form/select[@name=account]', 'Monthly');
     * ?>
     * ```
     *
     * Can select multiple options if second argument is array:
     *
     * ``` php
     * <?php
     * $I->selectOption('Which OS do you use?', array('Windows','Linux'));
     * ?>
     * ```
     *
     * @param $select
     * @param $option
     * @see Codeception\Util\Mink::selectOption()
     */
    public function selectOption($select, $option) {
        $step = new \Codeception\Step\Action('selectOption', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Ticks a checkbox.
     * For radio buttons use `selectOption` method.
     *
     * Example:
     *
     * ``` php
     * <?php
     * $I->checkOption('#agree');
     * ?>
     * ```
     *
     * @param $option
     * @see Codeception\Util\Mink::checkOption()
     */
    public function checkOption($option) {
        $step = new \Codeception\Step\Action('checkOption', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Unticks a checkbox.
     *
     * Example:
     *
     * ``` php
     * <?php
     * $I->uncheckOption('#notify');
     * ?>
     * ```
     *
     * @param $option
     * @see Codeception\Util\Mink::uncheckOption()
     */
    public function uncheckOption($option) {
        $step = new \Codeception\Step\Action('uncheckOption', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks that current uri contains a value
     *
     * ``` php
     * <?php
     * // to match: /home/dashboard
     * $I->seeInCurrentUrl('home');
     * // to match: /users/1
     * $I->seeInCurrentUrl('/users/');
     * ?>
     * ```
     *
     * @param $uri
    * Conditional Assertion: Test won't be stopped on fail
     * @see Codeception\Util\Mink::seeInCurrentUrl()
     */
    public function canSeeInCurrentUrl($uri) {
        $step = new \Codeception\Step\ConditionalAssertion('seeInCurrentUrl', func_get_args());
        return $this->scenario->runStep($step);
    }
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks that current uri contains a value
     *
     * ``` php
     * <?php
     * // to match: /home/dashboard
     * $I->seeInCurrentUrl('home');
     * // to match: /users/1
     * $I->seeInCurrentUrl('/users/');
     * ?>
     * ```
     *
     * @param $uri
     * @see Codeception\Util\Mink::seeInCurrentUrl()
     */
    public function seeInCurrentUrl($uri) {
        $step = new \Codeception\Step\Assertion('seeInCurrentUrl', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks that current uri does not contain a value
     *
     * ``` php
     * <?php
     * $I->dontSeeInCurrentUrl('/users/');
     * ?>
     * ```
     *
     * @param $uri
    * Conditional Assertion: Test won't be stopped on fail
     * @see Codeception\Util\Mink::dontSeeInCurrentUrl()
     */
    public function cantSeeInCurrentUrl($uri) {
        $step = new \Codeception\Step\ConditionalAssertion('dontSeeInCurrentUrl', func_get_args());
        return $this->scenario->runStep($step);
    }
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks that current uri does not contain a value
     *
     * ``` php
     * <?php
     * $I->dontSeeInCurrentUrl('/users/');
     * ?>
     * ```
     *
     * @param $uri
     * @see Codeception\Util\Mink::dontSeeInCurrentUrl()
     */
    public function dontSeeInCurrentUrl($uri) {
        $step = new \Codeception\Step\Assertion('dontSeeInCurrentUrl', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks that current url is equal to value.
     * Unlike `seeInCurrentUrl` performs a strict check.
     *
     * ``` php
     * <?php
     * // to match root url
     * $I->seeCurrentUrlEquals('/');
     * ?>
     * ```
     *
     * @param $uri
    * Conditional Assertion: Test won't be stopped on fail
     * @see Codeception\Util\Mink::seeCurrentUrlEquals()
     */
    public function canSeeCurrentUrlEquals($uri) {
        $step = new \Codeception\Step\ConditionalAssertion('seeCurrentUrlEquals', func_get_args());
        return $this->scenario->runStep($step);
    }
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks that current url is equal to value.
     * Unlike `seeInCurrentUrl` performs a strict check.
     *
     * ``` php
     * <?php
     * // to match root url
     * $I->seeCurrentUrlEquals('/');
     * ?>
     * ```
     *
     * @param $uri
     * @see Codeception\Util\Mink::seeCurrentUrlEquals()
     */
    public function seeCurrentUrlEquals($uri) {
        $step = new \Codeception\Step\Assertion('seeCurrentUrlEquals', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks that current url is not equal to value.
     * Unlike `dontSeeInCurrentUrl` performs a strict check.
     *
     * ``` php
     * <?php
     * // current url is not root
     * $I->dontSeeCurrentUrlEquals('/');
     * ?>
     * ```
     *
     * @param $uri
    * Conditional Assertion: Test won't be stopped on fail
     * @see Codeception\Util\Mink::dontSeeCurrentUrlEquals()
     */
    public function cantSeeCurrentUrlEquals($uri) {
        $step = new \Codeception\Step\ConditionalAssertion('dontSeeCurrentUrlEquals', func_get_args());
        return $this->scenario->runStep($step);
    }
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks that current url is not equal to value.
     * Unlike `dontSeeInCurrentUrl` performs a strict check.
     *
     * ``` php
     * <?php
     * // current url is not root
     * $I->dontSeeCurrentUrlEquals('/');
     * ?>
     * ```
     *
     * @param $uri
     * @see Codeception\Util\Mink::dontSeeCurrentUrlEquals()
     */
    public function dontSeeCurrentUrlEquals($uri) {
        $step = new \Codeception\Step\Assertion('dontSeeCurrentUrlEquals', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks that current url is matches a RegEx value
     *
     * ``` php
     * <?php
     * // to match root url
     * $I->seeCurrentUrlMatches('~$/users/(\d+)~');
     * ?>
     * ```
     *
     * @param $uri
    * Conditional Assertion: Test won't be stopped on fail
     * @see Codeception\Util\Mink::seeCurrentUrlMatches()
     */
    public function canSeeCurrentUrlMatches($uri) {
        $step = new \Codeception\Step\ConditionalAssertion('seeCurrentUrlMatches', func_get_args());
        return $this->scenario->runStep($step);
    }
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks that current url is matches a RegEx value
     *
     * ``` php
     * <?php
     * // to match root url
     * $I->seeCurrentUrlMatches('~$/users/(\d+)~');
     * ?>
     * ```
     *
     * @param $uri
     * @see Codeception\Util\Mink::seeCurrentUrlMatches()
     */
    public function seeCurrentUrlMatches($uri) {
        $step = new \Codeception\Step\Assertion('seeCurrentUrlMatches', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks that current url does not match a RegEx value
     *
     * ``` php
     * <?php
     * // to match root url
     * $I->dontSeeCurrentUrlMatches('~$/users/(\d+)~');
     * ?>
     * ```
     *
     * @param $uri
    * Conditional Assertion: Test won't be stopped on fail
     * @see Codeception\Util\Mink::dontSeeCurrentUrlMatches()
     */
    public function cantSeeCurrentUrlMatches($uri) {
        $step = new \Codeception\Step\ConditionalAssertion('dontSeeCurrentUrlMatches', func_get_args());
        return $this->scenario->runStep($step);
    }
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks that current url does not match a RegEx value
     *
     * ``` php
     * <?php
     * // to match root url
     * $I->dontSeeCurrentUrlMatches('~$/users/(\d+)~');
     * ?>
     * ```
     *
     * @param $uri
     * @see Codeception\Util\Mink::dontSeeCurrentUrlMatches()
     */
    public function dontSeeCurrentUrlMatches($uri) {
        $step = new \Codeception\Step\Assertion('dontSeeCurrentUrlMatches', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks that cookie is set.
     *
     * @param $cookie
     * @return mixed
    * Conditional Assertion: Test won't be stopped on fail
     * @see Codeception\Util\Mink::seeCookie()
     */
    public function canSeeCookie($cookie) {
        $step = new \Codeception\Step\ConditionalAssertion('seeCookie', func_get_args());
        return $this->scenario->runStep($step);
    }
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks that cookie is set.
     *
     * @param $cookie
     * @return mixed
     * @see Codeception\Util\Mink::seeCookie()
     */
    public function seeCookie($cookie) {
        $step = new \Codeception\Step\Assertion('seeCookie', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks that cookie doesn't exist
     *
     * @param $cookie
     * @return mixed
    * Conditional Assertion: Test won't be stopped on fail
     * @see Codeception\Util\Mink::dontSeeCookie()
     */
    public function cantSeeCookie($cookie) {
        $step = new \Codeception\Step\ConditionalAssertion('dontSeeCookie', func_get_args());
        return $this->scenario->runStep($step);
    }
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks that cookie doesn't exist
     *
     * @param $cookie
     * @return mixed
     * @see Codeception\Util\Mink::dontSeeCookie()
     */
    public function dontSeeCookie($cookie) {
        $step = new \Codeception\Step\Assertion('dontSeeCookie', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Sets a cookie.
     *
     * @param $cookie
     * @param $value
     * @return mixed
     * @see Codeception\Util\Mink::setCookie()
     */
    public function setCookie($cookie, $value) {
        $step = new \Codeception\Step\Action('setCookie', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Unsets cookie
     *
     * @param $cookie
     * @return mixed
     * @see Codeception\Util\Mink::resetCookie()
     */
    public function resetCookie($cookie) {
        $step = new \Codeception\Step\Action('resetCookie', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Grabs a cookie value.
     *
     * @param $cookie
     * @return mixed
     * @see Codeception\Util\Mink::grabCookie()
     */
    public function grabCookie($cookie) {
        $step = new \Codeception\Step\Action('grabCookie', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Takes a parameters from current URI by RegEx.
     * If no url provided returns full URI.
     *
     * ``` php
     * <?php
     * $user_id = $I->grabFromCurrentUrl('~$/user/(\d+)/~');
     * $uri = $I->grabFromCurrentUrl();
     * ?>
     * ```
     *
     * @param null $uri
     * @internal param $url
     * @return mixed
     * @see Codeception\Util\Mink::grabFromCurrentUrl()
     */
    public function grabFromCurrentUrl($uri = null) {
        $step = new \Codeception\Step\Action('grabFromCurrentUrl', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Attaches file from Codeception data directory to upload field.
     *
     * Example:
     *
     * ``` php
     * <?php
     * // file is stored in 'tests/_data/prices.xls'
     * $I->attachFile('input[@type="file"]', 'prices.xls');
     * ?>
     * ```
     *
     * @param $field
     * @param $filename
     * @see Codeception\Util\Mink::attachFile()
     */
    public function attachFile($field, $filename) {
        $step = new \Codeception\Step\Action('attachFile', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks if option is selected in select field.
     *
     * ``` php
     * <?php
     * $I->seeOptionIsSelected('#form input[name=payment]', 'Visa');
     * ?>
     * ```
     *
     * @param $selector
     * @param $optionText
     * @return mixed
    * Conditional Assertion: Test won't be stopped on fail
     * @see Codeception\Util\Mink::seeOptionIsSelected()
     */
    public function canSeeOptionIsSelected($select, $text) {
        $step = new \Codeception\Step\ConditionalAssertion('seeOptionIsSelected', func_get_args());
        return $this->scenario->runStep($step);
    }
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks if option is selected in select field.
     *
     * ``` php
     * <?php
     * $I->seeOptionIsSelected('#form input[name=payment]', 'Visa');
     * ?>
     * ```
     *
     * @param $selector
     * @param $optionText
     * @return mixed
     * @see Codeception\Util\Mink::seeOptionIsSelected()
     */
    public function seeOptionIsSelected($select, $text) {
        $step = new \Codeception\Step\Assertion('seeOptionIsSelected', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks if option is not selected in select field.
     *
     * ``` php
     * <?php
     * $I->dontSeeOptionIsSelected('#form input[name=payment]', 'Visa');
     * ?>
     * ```
     *
     * @param $selector
     * @param $optionText
     * @return mixed
    * Conditional Assertion: Test won't be stopped on fail
     * @see Codeception\Util\Mink::dontSeeOptionIsSelected()
     */
    public function cantSeeOptionIsSelected($select, $text) {
        $step = new \Codeception\Step\ConditionalAssertion('dontSeeOptionIsSelected', func_get_args());
        return $this->scenario->runStep($step);
    }
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks if option is not selected in select field.
     *
     * ``` php
     * <?php
     * $I->dontSeeOptionIsSelected('#form input[name=payment]', 'Visa');
     * ?>
     * ```
     *
     * @param $selector
     * @param $optionText
     * @return mixed
     * @see Codeception\Util\Mink::dontSeeOptionIsSelected()
     */
    public function dontSeeOptionIsSelected($select, $text) {
        $step = new \Codeception\Step\Assertion('dontSeeOptionIsSelected', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks that an input field or textarea contains value.
     * Field is matched either by label or CSS or Xpath
     *
     * Example:
     *
     * ``` php
     * <?php
     * $I->seeInField('Body','Type your comment here');
     * $I->seeInField('form textarea[name=body]','Type your comment here');
     * $I->seeInField('form input[type=hidden]','hidden_value');
     * $I->seeInField('#searchform input','Search');
     * $I->seeInField('//form/*[@name=search]','Search');
     * ?>
     * ```
     *
     * @param $field
     * @param $value
    * Conditional Assertion: Test won't be stopped on fail
     * @see Codeception\Util\Mink::seeInField()
     */
    public function canSeeInField($field, $value) {
        $step = new \Codeception\Step\ConditionalAssertion('seeInField', func_get_args());
        return $this->scenario->runStep($step);
    }
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks that an input field or textarea contains value.
     * Field is matched either by label or CSS or Xpath
     *
     * Example:
     *
     * ``` php
     * <?php
     * $I->seeInField('Body','Type your comment here');
     * $I->seeInField('form textarea[name=body]','Type your comment here');
     * $I->seeInField('form input[type=hidden]','hidden_value');
     * $I->seeInField('#searchform input','Search');
     * $I->seeInField('//form/*[@name=search]','Search');
     * ?>
     * ```
     *
     * @param $field
     * @param $value
     * @see Codeception\Util\Mink::seeInField()
     */
    public function seeInField($field, $value) {
        $step = new \Codeception\Step\Assertion('seeInField', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks that an input field or textarea doesn't contain value.
     * Field is matched either by label or CSS or Xpath
     * Example:
     *
     * ``` php
     * <?php
     * $I->dontSeeInField('Body','Type your comment here');
     * $I->dontSeeInField('form textarea[name=body]','Type your comment here');
     * $I->dontSeeInField('form input[type=hidden]','hidden_value');
     * $I->dontSeeInField('#searchform input','Search');
     * $I->dontSeeInField('//form/*[@name=search]','Search');
     * ?>
     * ```
     *
     * @param $field
     * @param $value
    * Conditional Assertion: Test won't be stopped on fail
     * @see Codeception\Util\Mink::dontSeeInField()
     */
    public function cantSeeInField($field, $value) {
        $step = new \Codeception\Step\ConditionalAssertion('dontSeeInField', func_get_args());
        return $this->scenario->runStep($step);
    }
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks that an input field or textarea doesn't contain value.
     * Field is matched either by label or CSS or Xpath
     * Example:
     *
     * ``` php
     * <?php
     * $I->dontSeeInField('Body','Type your comment here');
     * $I->dontSeeInField('form textarea[name=body]','Type your comment here');
     * $I->dontSeeInField('form input[type=hidden]','hidden_value');
     * $I->dontSeeInField('#searchform input','Search');
     * $I->dontSeeInField('//form/*[@name=search]','Search');
     * ?>
     * ```
     *
     * @param $field
     * @param $value
     * @see Codeception\Util\Mink::dontSeeInField()
     */
    public function dontSeeInField($field, $value) {
        $step = new \Codeception\Step\Assertion('dontSeeInField', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Finds and returns text contents of element.
     * Element is searched by CSS selector, XPath or matcher by regex.
     *
     * Example:
     *
     * ``` php
     * <?php
     * $heading = $I->grabTextFrom('h1');
     * $heading = $I->grabTextFrom('descendant-or-self::h1');
     * $value = $I->grabTextFrom('~<input value=(.*?)]~sgi');
     * ?>
     * ```
     *
     * @param $cssOrXPathOrRegex
     * @return mixed
     * @see Codeception\Util\Mink::grabTextFrom()
     */
    public function grabTextFrom($cssOrXPathOrRegex) {
        $step = new \Codeception\Step\Action('grabTextFrom', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Finds and returns field and returns it's value.
     * Searches by field name, then by CSS, then by XPath
     *
     * Example:
     *
     * ``` php
     * <?php
     * $name = $I->grabValueFrom('Name');
     * $name = $I->grabValueFrom('input[name=username]');
     * $name = $I->grabValueFrom('descendant-or-self::form/descendant::input[@name = 'username']');
     * ?>
     * ```
     *
     * @param $field
     * @return mixed
     * @see Codeception\Util\Mink::grabValueFrom()
     */
    public function grabValueFrom($field) {
        $step = new \Codeception\Step\Action('grabValueFrom', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks that page title contains text.
     *
     * ``` php
     * <?php
     * $I->seeInTitle('Blog - Post #1');
     * ?>
     * ```
     *
     * @param $title
     * @return mixed
    * Conditional Assertion: Test won't be stopped on fail
     * @see Codeception\Util\Mink::seeInTitle()
     */
    public function canSeeInTitle($title) {
        $step = new \Codeception\Step\ConditionalAssertion('seeInTitle', func_get_args());
        return $this->scenario->runStep($step);
    }
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks that page title contains text.
     *
     * ``` php
     * <?php
     * $I->seeInTitle('Blog - Post #1');
     * ?>
     * ```
     *
     * @param $title
     * @return mixed
     * @see Codeception\Util\Mink::seeInTitle()
     */
    public function seeInTitle($title) {
        $step = new \Codeception\Step\Assertion('seeInTitle', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks that page title does not contain text.
     *
     * @param $title
     * @return mixed
    * Conditional Assertion: Test won't be stopped on fail
     * @see Codeception\Util\Mink::dontSeeInTitle()
     */
    public function cantSeeInTitle($title) {
        $step = new \Codeception\Step\ConditionalAssertion('dontSeeInTitle', func_get_args());
        return $this->scenario->runStep($step);
    }
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks that page title does not contain text.
     *
     * @param $title
     * @return mixed
     * @see Codeception\Util\Mink::dontSeeInTitle()
     */
    public function dontSeeInTitle($title) {
        $step = new \Codeception\Step\Assertion('dontSeeInTitle', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     *
     * @see Codeception\Module::getName()
     */
    public function getName() {
        $step = new \Codeception\Step\Action('getName', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Enters a directory In local filesystem.
     * Project root directory is used by default
     *
     * @param $path
     * @see Codeception\Module\Filesystem::amInPath()
     */
    public function amInPath($path) {
        $step = new \Codeception\Step\Condition('amInPath', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Opens a file and stores it's content.
     *
     * Usage:
     *
     * ``` php
     * <?php
     * $I->openFile('composer.json');
     * $I->seeInThisFile('codeception/codeception');
     * ?>
     * ```
     *
     * @param $filename
     * @see Codeception\Module\Filesystem::openFile()
     */
    public function openFile($filename) {
        $step = new \Codeception\Step\Action('openFile', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Deletes a file
     *
     * ``` php
     * <?php
     * $I->deleteFile('composer.lock');
     * ?>
     * ```
     *
     * @param $filename
     * @see Codeception\Module\Filesystem::deleteFile()
     */
    public function deleteFile($filename) {
        $step = new \Codeception\Step\Action('deleteFile', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Deletes directory with all subdirectories
     *
     * ``` php
     * <?php
     * $I->deleteDir('vendor');
     * ?>
     * ```
     *
     * @param $dirname
     * @see Codeception\Module\Filesystem::deleteDir()
     */
    public function deleteDir($dirname) {
        $step = new \Codeception\Step\Action('deleteDir', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Copies directory with all contents
     *
     * ``` php
     * <?php
     * $I->copyDir('vendor','old_vendor');
     * ?>
     * ```
     *
     * @param $src
     * @param $dst
     * @see Codeception\Module\Filesystem::copyDir()
     */
    public function copyDir($src, $dst) {
        $step = new \Codeception\Step\Action('copyDir', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks If opened file has `text` in it.
     *
     * Usage:
     *
     * ``` php
     * <?php
     * $I->openFile('composer.json');
     * $I->seeInThisFile('codeception/codeception');
     * ?>
     * ```
     *
     * @param $text
    * Conditional Assertion: Test won't be stopped on fail
     * @see Codeception\Module\Filesystem::seeInThisFile()
     */
    public function canSeeInThisFile($text) {
        $step = new \Codeception\Step\ConditionalAssertion('seeInThisFile', func_get_args());
        return $this->scenario->runStep($step);
    }
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks If opened file has `text` in it.
     *
     * Usage:
     *
     * ``` php
     * <?php
     * $I->openFile('composer.json');
     * $I->seeInThisFile('codeception/codeception');
     * ?>
     * ```
     *
     * @param $text
     * @see Codeception\Module\Filesystem::seeInThisFile()
     */
    public function seeInThisFile($text) {
        $step = new \Codeception\Step\Assertion('seeInThisFile', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks the strict matching of file contents.
     * Unlike `seeInThisFile` will fail if file has something more then expected lines.
     * Better to use with HEREDOC strings.
     * Matching is done after removing "\r" chars from file content.
     *
     * ``` php
     * <?php
     * $I->openFile('process.pid');
     * $I->seeFileContentsEqual('3192');
     * ?>
     * ```
     *
     * @param $text
    * Conditional Assertion: Test won't be stopped on fail
     * @see Codeception\Module\Filesystem::seeFileContentsEqual()
     */
    public function canSeeFileContentsEqual($text) {
        $step = new \Codeception\Step\ConditionalAssertion('seeFileContentsEqual', func_get_args());
        return $this->scenario->runStep($step);
    }
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks the strict matching of file contents.
     * Unlike `seeInThisFile` will fail if file has something more then expected lines.
     * Better to use with HEREDOC strings.
     * Matching is done after removing "\r" chars from file content.
     *
     * ``` php
     * <?php
     * $I->openFile('process.pid');
     * $I->seeFileContentsEqual('3192');
     * ?>
     * ```
     *
     * @param $text
     * @see Codeception\Module\Filesystem::seeFileContentsEqual()
     */
    public function seeFileContentsEqual($text) {
        $step = new \Codeception\Step\Assertion('seeFileContentsEqual', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks If opened file doesn't contain `text` in it
     *
     * ``` php
     * <?php
     * $I->openFile('composer.json');
     * $I->dontSeeInThisFile('codeception/codeception');
     * ?>
     * ```
     *
     * @param $text
    * Conditional Assertion: Test won't be stopped on fail
     * @see Codeception\Module\Filesystem::dontSeeInThisFile()
     */
    public function cantSeeInThisFile($text) {
        $step = new \Codeception\Step\ConditionalAssertion('dontSeeInThisFile', func_get_args());
        return $this->scenario->runStep($step);
    }
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks If opened file doesn't contain `text` in it
     *
     * ``` php
     * <?php
     * $I->openFile('composer.json');
     * $I->dontSeeInThisFile('codeception/codeception');
     * ?>
     * ```
     *
     * @param $text
     * @see Codeception\Module\Filesystem::dontSeeInThisFile()
     */
    public function dontSeeInThisFile($text) {
        $step = new \Codeception\Step\Assertion('dontSeeInThisFile', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Deletes a file
     * @see Codeception\Module\Filesystem::deleteThisFile()
     */
    public function deleteThisFile() {
        $step = new \Codeception\Step\Action('deleteThisFile', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks if file exists in path.
     * Opens a file when it's exists
     *
     * ``` php
     * <?php
     * $I->seeFileFound('UserModel.php','app/models');
     * ?>
     * ```
     *
     * @param $filename
     * @param string $path
    * Conditional Assertion: Test won't be stopped on fail
     * @see Codeception\Module\Filesystem::seeFileFound()
     */
    public function canSeeFileFound($filename, $path = null) {
        $step = new \Codeception\Step\ConditionalAssertion('seeFileFound', func_get_args());
        return $this->scenario->runStep($step);
    }
    /**
     * -> This method is proxified to corresponding module.
     *
     * Checks if file exists in path.
     * Opens a file when it's exists
     *
     * ``` php
     * <?php
     * $I->seeFileFound('UserModel.php','app/models');
     * ?>
     * ```
     *
     * @param $filename
     * @param string $path
     * @see Codeception\Module\Filesystem::seeFileFound()
     */
    public function seeFileFound($filename, $path = null) {
        $step = new \Codeception\Step\Assertion('seeFileFound', func_get_args());
        return $this->scenario->runStep($step);
    }

 
    /**
     * -> This method is proxified to corresponding module.
     *
     * Erases directory contents
     *
     * ``` php
     * <?php
     * $I->cleanDir('logs');
     * ?>
     * ```
     *
     * @param $dirname
     * @see Codeception\Module\Filesystem::cleanDir()
     */
    public function cleanDir($dirname) {
        $step = new \Codeception\Step\Action('cleanDir', func_get_args());
        return $this->scenario->runStep($step);
    }
}

