before_script:
  - export ISOLATION=buildref${CI_BUILD_REF}$(echo ${CI_BUILD_REF_NAME} | tr -dc '[:alnum:]\n\r' | tr '[:upper:]' '[:lower:]')
  - export COMPOSE_PROJECT_NAME=${ISOLATION}

stages:
  - build
  - test
  - report
  - cleanup

build:
  stage: build
  script:
    - docker-compose build --pull

test-cli:
  stage: test
  script:
    - set +e
    - docker-compose run codeception run cli || EXIT_CODE=$?
    - set -e
    - cp -r _logs - cp -r /tmp/${ISOLATION}
    - exit EXIT_CODE

test-unit:
  stage: test
  script:
    - set +e
    - docker-compose run codeception run unit || EXIT_CODE=$?
    - set -e
    - cp -r _logs - cp -r /tmp/${ISOLATION}
    - exit EXIT_CODE

test-coverage:
  stage: test
  script:
    - set +e
    - docker-compose run codeception run coverage || EXIT_CODE=$?
    - set -e
    - cp -r _logs - cp -r /tmp/${ISOLATION}
    - exit EXIT_CODE

test-web:
  stage: test
  script:
    - export COMPOSE_PROJECT_NAME=${ISOLATION}${CI_BUILD_NAME}
    - docker-compose up -d
    - set +e
    - docker-compose run codeception run web || EXIT_CODE=$?
    - docker-compose kill
    - docker-compose rm -fv --all
    - docker-compose down
    - set -e
    - cp -r _logs - cp -r /tmp/${ISOLATION}
    - exit EXIT_CODE

test-angular:
  stage: test
  script:
    - export COMPOSE_PROJECT_NAME=${ISOLATION}${CI_BUILD_NAME}
    - docker-compose up -d
    - set +e
    - docker-compose run codeception run web || EXIT_CODE=$?
    - docker-compose kill
    - docker-compose rm -fv --all
    - docker-compose down
    - set -e
    - cp -r _logs - cp -r /tmp/${ISOLATION}
    - exit EXIT_CODE


report:
  stage: report
  when: always
  script:
    - cp -r /tmp/${ISOLATION} _logs
  artifacts:
    paths:
      - _logs

cleanup:
  stage: cleanup
  when: always
  script:
    - docker-compose kill
    - docker-compose rm -fv --all
    - docker-compose down
