---
image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_HUB_REGISTRY_IMAGE: codeception/codeception
  ALPINE_TAG: $CI_BUILD_REF_NAME-alpine
  ALPINE_IMAGE_TEST: $CI_REGISTRY_IMAGE:$ALPINE_TAG-test

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

build:alpine:
  stage: build
  script:
    - >
      docker build --rm
      --tag $ALPINE_IMAGE_TEST
      --file Dockerfile-alpine .
    - docker push $ALPINE_IMAGE_TEST

test_cli:alpine:
  stage: test
  script:
    - >
      docker run --rm
      --workdir /repo
      --volume $(pwd)/tests:/repo/tests
      --volume $(pwd)/codeception.yml:/repo/codeception.yml
      --volume $(pwd)/src:/repo/src
      $ALPINE_IMAGE_TEST run cli

test_command:alpine:
  stage: test
  script:
    - >
      docker run --rm
      --workdir /repo
      --volume $(pwd)/tests:/repo/tests
      --volume $(pwd)/codeception.yml:/repo/codeception.yml
      --volume $(pwd)/src:/repo/src
      $ALPINE_IMAGE_TEST run unit Codeception/Command

test_constraint:alpine:
  stage: test
  script:
    - >
      docker run --rm
      --workdir /repo
      --volume $(pwd)/tests:/repo/tests
      --volume $(pwd)/codeception.yml:/repo/codeception.yml
      --volume $(pwd)/src:/repo/src
      $ALPINE_IMAGE_TEST run unit Codeception/Constraints

deploy:alpine:
  stage: deploy
  script:
    - docker pull $ALPINE_IMAGE_TEST
    - docker tag $ALPINE_IMAGE_TEST $DOCKER_HUB_REGISTRY_IMAGE:$ALPINE_TAG
    - docker login -u $DOCKER_HUB_USER -p "$DOCKER_HUB_PASSWORD"
    - docker push $DOCKER_HUB_REGISTRY_IMAGE:$ALPINE_TAG
