before_script:
  - export ISOLATION=buildref${CI_BUILD_REF}$(echo ${CI_BUILD_REF_NAME} | tr -dc '[:alnum:]\n\r' | tr '[:upper:]' '[:lower:]')
  - export COMPOSE_PROJECT_NAME=${ISOLATION}

stages:
  - build
  - test
  - report
  - cleanup

build:
  stage: build
  script:
    - docker-compose build --pull

test:
  stage: test
  script:
    - docker-compose up -d
    - set -e
    - docker-compose run codeception run || EXIT_CODE=$?
    - set +e
    - cp -r _logs - cp -r /tmp/${ISOLATION}
    - exit EXIT_CODE

report:
  stage: report
  when: always
  script:
    - cp -r /tmp/${ISOLATION} _logs
  artifacts:
    paths:
      - _logs

cleanup:
  stage: cleanup
  when: always
  script:
    - docker-compose kill
    - docker-compose rm -fv --all
    - docker-compose down
