#!/usr/bin/php
<?php
/**
 * Codeception CLI
 */

if (!class_exists('UniversalClassLoader')) {
    $bootstrap_folder = (is_dir(__DIR__ . '/src'))
        ? dirname(__FILE__)
        : 'Codeception';

    require_once $bootstrap_folder.'/autoload.php';
}

use Symfony\Component\Console\Application,
    Symfony\Component\Console\Input\InputInterface,
    Symfony\Component\Console\Input\InputDefinition,
    Symfony\Component\Console\Input\InputOption;

 $app = new Application('Codeception', Codeception\Codecept::VERSION);
 $app->add(new Codeception\Command\Build('build'));
 $app->add(new Codeception\Command\Run('run'));
 $app->add(new Codeception\Command\Install('install'));
 $app->add(new Codeception\Command\Bootstrap('bootstrap'));
 $app->add(new Codeception\Command\GenerateScenarios('generate:scenarios'));
 $app->add(new Codeception\Command\GenerateCept('generate:test'));
 $app->add(new Codeception\Command\GenerateForClass('generate:for-class'));
 $app->run();