FROM php:7.4-cli

LABEL maintainer="Tobias Munk <tobias@diemeisterei.de>"

ENV CODECEPT_USER codecept

# Install required system packages
RUN apt-get update && \
    apt-get -y install \
            git \
            zlib1g-dev \
            libmemcached-dev \
            libpq-dev \
            libssl-dev \
            libxml2-dev \
            libzip-dev \
            unzip \
        --no-install-recommends && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install php extensions
RUN docker-php-ext-install \
    bcmath \
    mysqli \
    pdo pdo_mysql pdo_pgsql \
    soap \
    sockets \
    zip

# Install pecl extensions
RUN pecl install \
        apcu \
        memcached \
        mongodb \
        xdebug-2.9.5 && \
    docker-php-ext-enable \
        apcu.so \
        memcached.so \
        mongodb.so \
        xdebug

# Configure php
RUN echo "date.timezone = UTC" >> /usr/local/etc/php/php.ini

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- \
        --filename=composer \
        --install-dir=/usr/local/bin

# Add source-code
COPY . /repo

# Prepare application
WORKDIR /repo

ENV PATH /repo:${PATH}

RUN groupadd $CODECEPT_USER && \
    useradd -mg $CODECEPT_USER $CODECEPT_USER

USER $CODECEPT_USER

ENTRYPOINT ["codecept"]
