<?php  //[STAMP] 0cd1df4d2df44b67d43921c95f6ffb54
namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Codeception\Module\OrderHelper;

trait OrderGuyActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     *
     * @see \Codeception\Module\OrderHelper::failNow()
     */
    public function failNow() {
        return $this->getScenario()->runStep(new \Codeception\Step\Action('failNow', func_get_args()));
    }

 
    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     *
     * Conditional Assertion: Test won't be stopped on fail
     * @see \Codeception\Module\OrderHelper::seeFailNow()
     */
    public function canSeeFailNow() {
        return $this->getScenario()->runStep(new \Codeception\Step\ConditionalAssertion('seeFailNow', func_get_args()));
    }
    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     *
     * @see \Codeception\Module\OrderHelper::seeFailNow()
     */
    public function seeFailNow() {
        return $this->getScenario()->runStep(new \Codeception\Step\Assertion('seeFailNow', func_get_args()));
    }

 
    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     *
     * Conditional Assertion: Test won't be stopped on fail
     * @see \Codeception\Module\OrderHelper::dontSeeFailNow()
     */
    public function cantSeeFailNow() {
        return $this->getScenario()->runStep(new \Codeception\Step\ConditionalAssertion('dontSeeFailNow', func_get_args()));
    }
    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     *
     * @see \Codeception\Module\OrderHelper::dontSeeFailNow()
     */
    public function dontSeeFailNow() {
        return $this->getScenario()->runStep(new \Codeception\Step\Assertion('dontSeeFailNow', func_get_args()));
    }

 
    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     *
     * @see \Codeception\Module\OrderHelper::writeToFile()
     */
    public function writeToFile($text) {
        return $this->getScenario()->runStep(new \Codeception\Step\Action('writeToFile', func_get_args()));
    }

 
    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     *
     * @see \Codeception\Module\OrderHelper::appendToFile()
     */
    public function appendToFile($marker) {
        return $this->getScenario()->runStep(new \Codeception\Step\Action('appendToFile', func_get_args()));
    }
}
