<?php  //[STAMP] d1f75312f814964e4c9a86f78630dd7c
namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Codeception\Module\OrderHelper;

trait OrderGuyActions
{
   
    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     *
     * @see \Codeception\Module\OrderHelper::failNow()
     */
    public function failNow() {
        return $this->scenario->runStep(new \Codeception\Step\Action('failNow', func_get_args()));
    }

 
    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     *
     * @see \Codeception\Module\OrderHelper::writeToFile()
     */
    public function writeToFile($text) {
        return $this->scenario->runStep(new \Codeception\Step\Action('writeToFile', func_get_args()));
    }

 
    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     *
     * @see \Codeception\Module\OrderHelper::appendToFile()
     */
    public function appendToFile($marker) {
        return $this->scenario->runStep(new \Codeception\Step\Action('appendToFile', func_get_args()));
    }
}