<?php  //[STAMP] bfe49b07ac3a9ebf49500e14ba1e0c8e
namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Codeception\Module\SkipHelper;

trait SkipGuyActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}