<?php  //[STAMP] aae3ba8f24a75add3b16a8c20352acba
namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Codeception\Module\SkipHelper;

trait SkipGuyActions
{
   
}