<?php
// This class was automatically generated by build task
// You can change it manually, but it will be overwritten on next build

/**

 * Methods from Filesystem
 * @method CliGuy amInPath($path)
 * @method CliGuy openFile($filename)
 * @method CliGuy deleteFile($filename)
 * @method CliGuy deleteDir($dirname)
 * @method CliGuy seeInThisFile($text)
 * @method CliGuy dontSeeInThisFile($text)
 * @method CliGuy deleteThisFile()
 * @method CliGuy seeFileFound($filename)
 * 
 * Methods from Cli
 * @method CliGuy runShellCommmand($command)
 * @method CliGuy seeInShellOutput($text)
 * @method CliGuy dontSeeInShellOutput($text)
 * 
 * Methods from CliHelper
 * @method CliGuy executeCommand($command)
**/


class CliGuy extends \Codeception\AbstractGuy
{


}

