<?php
// This class was automatically generated by build task
// You can change it manually, but it will be overwritten on next build

/**

 * Methods from \Codeception\Module\Filesystem
 * @method CliGuy openFile($filename)
 * @method CliGuy seeInFile($text)
 * @method CliGuy dontSeeInFile($text)
 * @method CliGuy seeFileFound($filename)
 * 
 * Methods from \Codeception\Module\Cli
 * @method CliGuy amInPath($dir)
 * @method CliGuy runShellCommmand($command)
 * @method CliGuy seeInShellOutput($text)
 * @method CliGuy dontSeeInShellOutput($text)
 * 
 * Methods from \Codeception\AbstractGuy
 * @method CliGuy wantToTest($text)
 * @method CliGuy wantTo($text)
 * @method CliGuy amTesting($method)
 * @method CliGuy amTestingMethod($method)
 * @method CliGuy testMethod($signature)
 * @method CliGuy expectTo($prediction)
 * @method CliGuy expect($prediction)
 * @method CliGuy amGoingTo($argumentation)
**/


class CliGuy extends \Codeception\AbstractGuy
{


}

