<?php
// This class was automatically generated by build task
// You can change it manually, but it will be overwritten on next build

/**

 * Methods from \Codeception\Module\PhpBrowser
 * @method WebGuy submitForm($selector, $params)
 * @method WebGuy sendAjaxPostRequest($uri, $params)
 * @method WebGuy sendAjaxGetRequest($uri, $params)
 * @method WebGuy amOnPage($page)
 * @method WebGuy dontSee($text)
 * @method WebGuy see($text)
 * @method WebGuy click($link)
 * @method WebGuy reloadPage()
 * @method WebGuy moveBack()
 * @method WebGuy moveForward()
 * @method WebGuy fillField($field, $value)
 * @method WebGuy fillFields($fields)
 * @method WebGuy selectOption($select, $option)
 * @method WebGuy checkOption($option)
 * @method WebGuy uncheckOption($option)
 * @method WebGuy attachFileToField($field, $path)
 * @method WebGuy seeInCurrentAddress($uri)
 * @method WebGuy seeCheckboxIsChecked($checkbox)
 * @method WebGuy dontSeeCheckboxIsChecked($checkbox)
 * @method WebGuy seeInField($field, $value)
 * @method WebGuy dontSeeInField($field, $value)
 * 
 * Methods from \Codeception\Module\WebHelper
 * 
 * Methods from \Codeception\AbstractGuy
 * @method WebGuy wantToTest($text)
 * @method WebGuy wantTo($text)
 * @method WebGuy amTestingClass($text)
 * @method WebGuy amTesting($method)
 * @method WebGuy amTestingMethod($method)
 * @method WebGuy testMethod($signature)
 * @method WebGuy expectTo($prediction)
 * @method WebGuy amGoingTo($argumentation)
**/


class WebGuy extends \Codeception\AbstractGuy
{


}

