<?php
// This class was automatically generated by build task
// You can change it manually, but it will be overwritten on next build

/**

 * Methods from \Codeception\Module\PhpBrowser
 * @method void submitForm($selector, $params)
 * @method void sendAjaxPostRequest($uri, $params)
 * @method void sendAjaxGetRequest($uri, $params)
 * @method void amOnPage($page)
 * @method void dontSee($text)
 * @method void see($text)
 * @method void click($link)
 * @method void reloadPage()
 * @method void moveBack()
 * @method void moveForward()
 * @method void fillField($field, $value)
 * @method void fillFields($fields)
 * @method void selectOption($select, $option)
 * @method void checkOption($option)
 * @method void uncheckOption($option)
 * @method void attachFileToField($field, $path)
 * @method void seeInCurrentAddress($uri)
 * @method void seeCheckboxIsChecked($checkbox)
 * @method void dontSeeCheckboxIsChecked($checkbox)
 * @method void seeInField($field, $value)
 * @method void dontSeeInField($field, $value)
 * 
 * Methods from \Codeception\Module\WebHelper
**/


class WebGuy extends \Codeception\AbstractGuy
{


}

