<?php
// This class was automatically generated by build task
// You can change it manually, but it will be overwritten on next build

/**

 * Methods from Filesystem
 * @method TestGuy openFile($filename)
 * @method TestGuy seeInFile($text)
 * @method TestGuy dontSeeInFile($text)
 * @method TestGuy seeFileFound($filename)
 * 
 * Methods from TestHelper
**/


class TestGuy extends \Codeception\AbstractGuy
{


}

