<?php
// This class was automatically generated by build task
// You can change it manually, but it will be overwritten on next build

/**

 * Methods from Filesystem
 * @method TestGuy amInPath($path)
 * @method TestGuy openFile($filename)
 * @method TestGuy deleteFile($filename)
 * @method TestGuy deleteDir($dirname)
 * @method TestGuy seeInThisFile($text)
 * @method TestGuy dontSeeInThisFile($text)
 * @method TestGuy deleteThisFile()
 * @method TestGuy seeFileFound($filename)
 * 
 * Methods from TestHelper
**/


class TestGuy extends \Codeception\AbstractGuy
{


}

