<?php
// This class was automatically generated by build task
// You can change it manually, but it will be overwritten on next build

/**

 * Methods from \Codeception\Module\Filesystem
 * @method TestGuy openFile($filename)
 * @method TestGuy seeInFile($text)
 * @method TestGuy dontSeeInFile($text)
 * @method TestGuy seeFileFound($filename)
 * 
 * Methods from \Codeception\Module\TestHelper
 * 
 * Methods from \Codeception\AbstractGuy
 * @method TestGuy wantToTest($text)
 * @method TestGuy wantTo($text)
 * @method TestGuy amTestingClass($text)
 * @method TestGuy amTesting($method)
 * @method TestGuy amTestingMethod($method)
 * @method TestGuy testMethod($signature)
 * @method TestGuy expectTo($prediction)
 * @method TestGuy amGoingTo($argumentation)
**/


class TestGuy extends \Codeception\AbstractGuy
{


}

