paths:
    tests: tests
    output: tests/_log
    helpers: tests/helpers
    modules: tests/modules
settings:
    bootstrap: _bootstrap.php
    suite_class: \PHPUnit_Framework_TestSuite
    colors: true
    silent: false
    memory_limit: 1024M
    silent: false
    error_level: E_ALL | E_STRICT