<?php
// This class was automatically generated by build task
// You can change it manually, but it will be overwritten on next build

/**

 * Methods from DumbHelper
**/


class DumbGuy extends \Codeception\AbstractGuy
{


}

