<?php
// This class was automatically generated by build task
// You can change it manually, but it will be overwritten on next build

/**

 * Methods from Unit
 * @method CodeGuy testMethod($signature)
 * @method CodeGuy haveFakeClass($instance)
 * @method CodeGuy haveStub($instance)
 * @method CodeGuy executeTestedMethodOn($object)
 * @method CodeGuy executeTestedMethodWith($params)
 * @method CodeGuy executeTestedMethod()
 * @method CodeGuy execute($code)
 * @method CodeGuy executeMethod($object, $method)
 * @method CodeGuy changeProperties($obj)
 * @method CodeGuy changeProperty($obj, $property, $value)
 * @method CodeGuy seeExceptionThrown($classname)
 * @method CodeGuy seeMethodInvoked($mock, $method)
 * @method CodeGuy seeMethodInvokedOnce($mock, $method)
 * @method CodeGuy seeMethodNotInvoked($mock, $method)
 * @method CodeGuy seeMethodInvokedMultipleTimes($mock, $method, $times)
 * @method CodeGuy seeResultEquals($value)
 * @method CodeGuy seeResultContains($value)
 * @method CodeGuy dontSeeResultContains($value)
 * @method CodeGuy dontSeeResultEquals($value)
 * @method CodeGuy seeEmptyResult()
 * @method CodeGuy seeResultIs($type)
 * @method CodeGuy seePropertyEquals($object, $property, $value)
 * @method CodeGuy seePropertyIs($object, $property, $type)
 * @method CodeGuy seeMethodReturns($object, $method, $value)
 * @method CodeGuy seeMethodNotReturns($object, $method, $value)
 * 
 * Methods from CodeHelper
 * 
 * Methods from EmulateModuleHelper
 * @method CodeGuy seeEquals($expected, $actual)
 * @method CodeGuy seeFeaturesEquals($expected)
**/


class CodeGuy extends \Codeception\AbstractGuy
{


}

