<?php //[STAMP] b49e89c567bf4e108bd6902de0f4fa39

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile


use Codeception\Module\OrderHelper;

/**
 * Inherited Methods
 * @method void wantToTest($text)
 * @method void wantTo($text)
 * @method void expectTo($prediction)
 * @method void expect($prediction)
 * @method void amGoingTo($argumentation)
 * @method void am($role)
 * @method void lookForwardTo($achieveValue)
 * @method void comment($description)
 * @method void haveFriend($name)
*/
class OrderGuy extends \Codeception\Actor
{
   
    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     *
     * @see \Codeception\Module\OrderHelper::failNow()
     */
    public function failNow() {
        return $this->scenario->runStep(new \Codeception\Step\Action('failNow', func_get_args()));
    }

 
    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     *
     * @see \Codeception\Module\OrderHelper::writeToFile()
     */
    public function writeToFile($text) {
        return $this->scenario->runStep(new \Codeception\Step\Action('writeToFile', func_get_args()));
    }

 
    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     *
     * @see \Codeception\Module\OrderHelper::appendToFile()
     */
    public function appendToFile($marker) {
        return $this->scenario->runStep(new \Codeception\Step\Action('appendToFile', func_get_args()));
    }
}
